# Generated by Django 3.1.1 on 2020-09-21 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='tender',
        ),
    ]
