# Generated by Django 3.1.1 on 2020-09-21 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_remove_purchaseorder_tender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
    ]
