# Generated by Django 3.1.1 on 2020-09-21 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TenderPost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('SC', 'Successful')], default='PD', max_length=2)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenderPost.tenderbid')),
            ],
        ),
    ]
