# Generated by Django 3.1.1 on 2020-09-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenderPost', '0002_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='received_date',
            field=models.DateField(null=True),
        ),
    ]
