# Generated by Django 3.1.1 on 2020-09-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenderPost', '0003_purchaseorder_received_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('SC', 'Successful'), ('CC', 'Cancelled')], default='PD', max_length=2),
        ),
    ]
