# Generated by Django 3.1.1 on 2020-09-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='registration_number',
            new_name='registration_num',
        ),
    ]
